jenkins:
    securityRealm:
        local:
            allowsSignup: false
            users:
                - id: "${JENKINS_ADMIN_ID}"
                  password: "${JENKINS_ADMIN_PASSWORD}"



    projectNamingStrategy:
        roleBased:
            forceExistingJobs: true

    authorizationStrategy:
        roleBased:
            roles:
                global:
                    - name: "Admin"
                      description: "Jenkins administrators"
                      pattern: ".*"
                      permissions:
                          - "Overall/Administer"
                          - "Job/Create"
                          - "Job/Read"
                          - "Job/Build"
                          - "Job/Cancel"
                          - "Job/Delete"
                          - "View/Configure"
                          - "View/Create"
                      entries:
                          - user: "${JENKINS_ADMIN_ID}"

credentials:
    system:
        domainCredentials:
            - credentials:
                  - string:
                        scope: GLOBAL
                        id: "database-url"
                        secret: "${DATABASE_URL}"
                        description: "Database URL"
                  - string:
                        scope: GLOBAL
                        id: "database-user"
                        secret: "${DATABASE_USER}"
                        description: "Database User"
                  - string:
                        scope: GLOBAL
                        id: "database-password"
                        secret: "${DATABASE_PASSWORD}"
                        description: "Database Password"
                  - string:
                        scope: GLOBAL
                        id: "server-url"
                        secret: "${SERVER_URL}"
                        description: "Server URL"
                  - string:
                        scope: GLOBAL
                        id: "server-port"
                        secret: "${SERVER_PORT}"
                        description: "Server Port"
                  - string:
                        scope: GLOBAL
                        id: "refresh-token-expiration-date"
                        secret: "${REFRESH_TOKEN_EXPIRATION_DATE}"
                        description: "Refresh Token Expiration Date"
                  - string:
                        scope: GLOBAL
                        id: "json-token-signing-key"
                        secret: "${JSON_TOKEN_SIGNING_KEY}"
                        description: "JSON Token Signing Key"
                  - string:
                        scope: GLOBAL
                        id: "s3-endpoint-url"
                        secret: "${S3_ENDPOINT_URL}"
                        description: "S3 Endpoint URL"
                  - string:
                        scope: GLOBAL
                        id: "s3-access-key"
                        secret: "${S3_ACCESS_KEY}"
                        description: "S3 Access Key"
                  - string:
                        scope: GLOBAL
                        id: "s3-bucket-name"
                        secret: "${S3_BUCKET_NAME}"
                        description: "S3 Bucket Name"
                  - string:
                        scope: GLOBAL
                        id: "jenkins-admin-email"
                        secret: "${JENKINS_ADMIN_EMAIL}"
                        description: "Jenkins Admin Email"

jobs:
  - script: >
      pipelineJob('I am pupil API') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url('https://github.com/baldehshnik/im-pupil-doc.git')
                          }

                          branch('main')
                      }
                  }

                  scriptPath('Jenkinsfile.groovy')
              }
          }
      }

unclassified:
  mailer:
    authentication:
      password: "${JENKINS_SENDER_PASSWORD}"
      username: "${JENKINS_SENDER_EMAIL}"
    charset: "UTF-8"
    smtpHost: "smtp.gmail.com"
    smtpPort: "465"
    useSsl: true
    useTls: false

  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultContentType: "text/plain"
    mailAccount:
      smtpHost: "smtp.gmail.com"
      smtpPort: "465"
      smtpUsername: "${JENKINS_SENDER_EMAIL}"
      smtpPassword: "${JENKINS_SENDER_PASSWORD}"
      useSsl: true
      useTls: false
      useOAuth2: false












