services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - ./casc.yaml:/var/jenkins_home/casc.yaml
      - ./Jenkinsfile.groovy:/var/jenkins_home/Jenkinsfile.groovy
      - ./setup.groovy:/var/jenkins_home/init.groovy.d/setup.groovy

volumes:
  jenkins_home: